/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shop/' | '/api/public/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shop' | '/api/public/waitlist'
  id: '__root__' | '/' | '/shop/' | '/api/public/waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
